### ISSUE TITLE
Panic in `broker.go` - invalid memory address or nil pointer reference [v0.10.2 - line 234]

### ISSUE THREAD

**Issue by Ferix9288** [twmb/franz-go#93] opened 2021-10-12 07:35 UTC
@twmb  - First and foremost, would like to say thanks for this great `kafka go` library. The API for `consumer/producer`, as well as utilizing the hooks for metrics, are extremely intuitive and easy to implement compared to Confluent, Sarama, and Segmentio. Additionally, it has been blazingly fast and sufficient for our company's usecase.

However unfortunately, we did come across this `panic` in `franz-go` library and would like your insight as to what may have happened before pushing this to production.

Note: 
- Version-wise : it was running on v0.10.2
- However when comparing to latest code in `master`, it appears the same issue may persist as there hasn't been that many modifications to `broker.go`

## Panic Trace 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x8c3e8f]

goroutine 93 [running]:
github.com/twmb/franz-go/pkg/kgo.(*broker).do(0x0, 0xe3bc90, 0xc00022ea40, 0xe42b18, 0xc00022ea00, 0xc0006d8320)
	/go/pkg/mod/github.com/twmb/franz-go@v0.10.2/pkg/kgo/broker.go:234 +0x4f
github.com/twmb/franz-go/pkg/kgo.(*broker).waitResp(0x0, 0xe3bc90, 0xc00022ea40, 0xe42b18, 0xc00022ea00, 0x0, 0x0, 0xe2f420, 0xc00027e320)
	/go/pkg/mod/github.com/twmb/franz-go@v0.10.2/pkg/kgo/broker.go:256 +0xfc
github.com/twmb/franz-go/pkg/kgo.(*retriable).Request(0xc00083d298, 0xe3bc90, 0xc00022ea40, 0xe42b18, 0xc00022ea00, 0x4ed62c, 0xc000298000, 0x0, 0xc00083d2c0)
	/go/pkg/mod/github.com/twmb/franz-go@v0.10.2/pkg/kgo/client.go:617 +0x4f5
github.com/twmb/franz-go/pkg/kgo.(*Client).handleReqWithCoordinator(0xc00017cd80, 0xe3bc90, 0xc00022ea40, 0xc00022ea80, 0x0, 0xc000132db0, 0x10, 0xe42b18, 0xc00022ea00, 0x73, ...)
	/go/pkg/mod/github.com/twmb/franz-go@v0.10.2/pkg/kgo/client.go:1227 +0x109
github.com/twmb/franz-go/pkg/kgo.(*Client).handleCoordinatorReqSimple(0xc00017cd80, 0xe3bc90, 0xc00022ea40, 0x3837343530393800, 0xc000132db0, 0x10, 0xe42b18, 0xc00022ea00, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/twmb/franz-go@v0.10.2/pkg/kgo/client.go:1160 +0x151
github.com/twmb/franz-go/pkg/kgo.(*Client).handleCoordinatorReq(0xc00017cd80, 0xe3bc90, 0xc00022ea40, 0xe42b18, 0xc00022ea00, 0xc00022ea00, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/twmb/franz-go@v0.10.2/pkg/kgo/client.go:1144 +0xb4d
github.com/twmb/franz-go/pkg/kgo.(*Client).shardedRequest(0xc00017cd80, 0xe3bc90, 0xc00022ea40, 0xe42b18, 0xc00022ea00, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/twmb/franz-go@v0.10.2/pkg/kgo/client.go:772 +0x848
github.com/twmb/franz-go/pkg/kgo.(*Client).Request(0xc00017cd80, 0xe3bc90, 0xc00015a840, 0xe42b18, 0xc00022ea00, 0x2, 0x2, 0x1, 0x0)
	/go/pkg/mod/github.com/twmb/franz-go@v0.10.2/pkg/kgo/client.go:562 +0x57
github.com/twmb/franz-go/pkg/kmsg.(*HeartbeatRequest).RequestWith(...)
	/go/pkg/mod/github.com/twmb/franz-go/pkg/kmsg@v0.0.0-20210823212011-0d01f7456b4d/generated.go:11933
github.com/twmb/franz-go/pkg/kgo.(*groupConsumer).heartbeat(0xc0003160e0, 0x0, 0xc000410228, 0x0, 0x0)
	/go/pkg/mod/github.com/twmb/franz-go@v0.10.2/pkg/kgo/consumer_group.go:750 +0xaee
github.com/twmb/franz-go/pkg/kgo.(*groupConsumer).setupAssignedAndHeartbeat.func1(0xc00040c5f0, 0xc0003160e0, 0xc000403560, 0xc0004035c0, 0xc000410228)
	/go/pkg/mod/github.com/twmb/franz-go@v0.10.2/pkg/kgo/consumer_group.go:634 +0x12f
created by github.com/twmb/franz-go/pkg/kgo.(*groupConsumer).setupAssignedAndHeartbeat
	/go/pkg/mod/github.com/twmb/franz-go@v0.10.2/pkg/kgo/consumer_group.go:631 +0x366
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x8c3e8f
```

## Analysis 

Main takeaway are these lines:
```
github.com/twmb/franz-go/pkg/kgo.(*broker).do(0x0, 0xe3bc90, 0xc00022ea40, 0xe42b18, 0xc00022ea00, 0xc0006d8320)
github.com/twmb/franz-go/pkg/kgo.(*broker).waitResp(0x0, 0xe3bc90, 0xc00022ea40, 0xe42b18, 0xc00022ea00, 0x0, 0x0, 0xe2f420, 0xc00027e320)
```

Where `this`[*broker] is pointing to address `0x0` (`nil`). Hence at `line:234`, it blows up:
```
	b.dieMu.RLock() // this line
	if atomic.LoadInt32(&b.dead) == 1 {
		dead = true
	} else {
		b.reqs <- promisedReq{ctx, req, promise, enqueue}
	}
```

Reference: https://stackoverflow.com/questions/36459827/how-to-interpret-go-stacktrace

## Experimentation, Speculation, and Further Investigation

I thought it peculiar that a `nil` pointer could jump from `waitResp` to `do` but apparently in `go`, this is ok. See `go playground` below. My hunch is because `go` sees `struct pointer` methods as simply function addresses and can jump to it even if the instance is `nil`.
https://play.golang.org/p/U9myX5ub_E8

Therefore, has to be some race condition or logical error that potentially caused this `*broker` to be nil. 

- I checked usage of client.brokers map, and all locations seem properly guarded with read or write lock
- I have another theory but this comment is getting long. Will follow up in another

## Extra Info 
Some more details that might help:
- Code-wise, we are spinning up two `kgo.NewClient` for better code separation between `producer` and `consumer` [hidden behind as interfaces]
- This happened during load testing, unable to replicate yet
- Topics that it's currently producing & consuming may have been deleted during the load test; don't quite remember

**Comment by Ferix9288** [comment] 2021-10-12 07:58
Here's what looks like the most common path for calling `broker.waitResp`: 

client.go:609
```
	if err == nil {
		resp, err = r.last.waitResp(ctx, req)
		if err == nil && r.parseRetryErr != nil {
			retryErr = r.parseRetryErr(resp)
		}
	}
```

last looks like it's based on this retriable function (client.go:293-315):

```
// broker returns a random broker from all brokers ever known.
func (cl *Client) broker() *broker {
	cl.brokersMu.Lock() // full lock needed for anyBrokerIdx below
	defer cl.brokersMu.Unlock()

	b, exists := cl.brokers[cl.anyBrokerIdx]
	if !exists && cl.anyBrokerIdx != 0 {
		cl.anyBrokerIdx = 0
		b, exists = cl.brokers[cl.anyBrokerIdx]
	}
	cl.anyBrokerIdx++

	// Maybe we have not loaded brokers yet--fallback to seeds.
	if !exists {
		b, exists = cl.brokers[unknownSeedID(int(cl.anySeedIdx))]
		if !exists {
			cl.anySeedIdx = 0 // seed 0 **must** exists.
			b = cl.brokers[unknownSeedID(int(cl.anySeedIdx))]
		}
		cl.anySeedIdx++
	}

	return b
}
```

My speculation is that you return an address to this pointer for this method, but in a parallel goroutine, `updateBrokers` somehow nukes this address?

client.go:439-444
```
			// delete the broker to avoid stopping it below in goneBrokers
			delete(cl.brokers, broker.NodeID)
			if !b.meta.equals(broker) {
				b.stopForever()
				b = cl.newBroker(broker.NodeID, broker.Host, broker.Port, broker.Rack)
			}
```  

What do you think? Can these two methods be run in parallel, and could garbage collector mistakenly cleans up this address?

-----
Alternatively, it could also be that maybe broker is still `nil` here:

client.go:309
```
		if !exists {
			cl.anySeedIdx = 0 // seed 0 **must** exists.
			b = cl.brokers[unknownSeedID(int(cl.anySeedIdx))]
		}
```

**Comment by twmb** [comment] 2021-10-12 15:54
How reproducible is this, and are you running against Kafka or a reimplementation (Redpanda, AWS MSK, etc)?

The underlying code for setting brokers is really straightforward and it's all guarded with locks. No nil value can end up in the brokers map, and all loads look to always check if the load is nil. I'm wondering if there's an indirect load somewhere that is not checked, though.

I've taken a look at all commits from v0.10.2 through latest. Nothing outright annotates a fix for what you're experiencing, but I _think_ you may be experiencing a bug that was fixed in [v0.10.3](https://github.com/twmb/franz-go/blob/master/CHANGELOG.md#v0103):  307c22ea624ff50fd30c06c1d69606b3d40320a4 fixed a bug in the retriable req code path where the wrong error was kept.

The flow:
1) we load a broker and issue a request, the request fails
2) the error is retriable, in v0.10.2 on line 632 we reload the broker again.
3) The broker load errored, so we have a nil broker and an error saved into the `err` variable (_not_ `nextErr`)
4) we loop back to the top (with a goto)
5) `nextErr` is saved into `err`, and `nextErr` is nil, so now we have a nil broker and no error
6) this nil broker is used, the request is issued, a panic happens

Can you try updating to v0.10.3, or better, v1.1.4? v0.10.3 should fix this direct bug. If it's reproducible for you, that's great. I suspect it could be caused by having the coordinator broker for a group initially available, and then after some time, unavailable.

**Comment by twmb** [comment] 2021-10-12 21:28
That sounds like the default metadata poll interval. The client internally reaps connections that have no reads nor writes for the last 20s every 20s. Per broker, there are three potential connections: 1 for producing, 1 for fetching, 1 for anything else. It looks like broker 2 is the coordinator for your group, so all group requests are going to that. After 5 minutes a metadata request caused a new connection to open on broker 1. After 20s that connection will be reaped.

**Closed as completed** 2021-10-13 16:15 UTC

**Comment by Ferix9288** [comment] 2021-10-13 19:49
Of course, thanks and will do! Quick follow up to this is that I've been soaking since with the upgraded version and found no issues / no errors (~ 1.5 days)
