### ISSUE TITLE
kmsg.NewListGroupsRequest returns duplicates of consumer groups

### ISSUE THREAD

**Issue by pawelcit** [twmb/franz-go#567] opened 2023-09-19 18:13 UTC
I have 3 different kafka clusters and I noticed that on one of them I get duplicates of consumer groups in the reply. 
Does anyone know what could be causing that?

```
package main

import (
	"context"
	"fmt"
	"time"

	"github.com/twmb/franz-go/pkg/kgo"
	"github.com/twmb/franz-go/pkg/kmsg"
	"github.com/twmb/franz-go/pkg/kversion"
)

func main() {
	seeds := []string{"127.0.0.1:9092"}
	client, err := kgo.NewClient(
		kgo.SeedBrokers(seeds...),

		kgo.MaxVersions(kversion.V2_4_0()),
	)
	if err != nil {
		panic(err)
	}
	defer client.Close()

	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	{
		req := kmsg.NewListGroupsRequest()

		res, err := req.RequestWith(ctx, client)
		if err != nil {
			panic(err)
		}

		groupIDs := make([]string, len(res.Groups))
		for i, group := range res.Groups {
			groupIDs[i] = group.Group
			fmt.Printf("%+v\n",group.Group)
		}
	}
}
```

**Comment by twmb** [comment] 2023-09-19 20:36
What are the debug logs? Also what's the difference if you use RequestSharded?

**Comment by pcituk** [comment] 2023-09-19 21:03
@twmb Could you please advise how to use RequestSharded and enable debug logs in this case? 

If by the debug logs you meant how I discovered the issue then I just saved an output to a file (thousands of consumer groups) and run

`cat log.txt | sort | uniq -c | sort -rn `

**Comment by twmb** [comment] 2023-09-20 23:14
If I run this program against a cluster, I don't receive duplicate groups.
Debug logs for this case can be easily printed with `kgo.WithLogger(kgo.BasicLogger(os.Stderr, kgo.LogLevelDebug, nil))`.
For each resp in RequestSharded, print the groups from `Resp.(*kmsg.ListGroupsResponse)` (so long as the `.Err` field is non-nil.

**Comment by pawelcit** [comment] 2023-09-21 10:14
First of all please bare in mind I'm not experienced Go developer. Because I couldn't find any documentation about this library I tried to use examples and the code from kminion but without success (have no idea how to use RequestSharded properly) This is what I tried:

```
	{
		req := kmsg.NewListGroupsRequest()
		// req := kmsg.NewDescribeGroupsRequest() 

		res := client.RequestSharded(ctx, &req)

		for _, kresp := range res {
			res := kresp.Resp.(*kmsg.DescribeGroupsResponse)
			fmt.Printf("%+v\n",res)
		}


	}
```

If I use kmsg.NewDescribeGroupsRequest() I get:
`&{Version:5 ThrottleMillis:0 Groups:[] UnknownTags:{keyvals:map[]}}`

If use kmsg.NewListGroupsRequest() I get:
```
panic: interface conversion: kmsg.Response is *kmsg.ListGroupsResponse, not *kmsg.DescribeGroupsResponse

goroutine 1 [running]:
```

Let me start from the beginning. The problem originates from kminion which I tried to deploy to my environment. Unfortunately the exporter didn't work with one of my clusters and didn't generate any metrics. No errors on stdout (debug: info or debug) only http 500 code as a response along with thousands messages like:
`* collected metric "kafka_minion_kafka_consumer_group_info" { label:{name:"coordinator_id" value:"0"} label:{name:"group_id" value:"prod-application_addr"} label:{name:"protocol" value:"cooperative-sticky"} label:{name:"protocol_type" value:"consumer"} label:{name:"state" value:"Stable"} gauge:{value:1}} was collected before with the same name and label values`

I started analysing the kminion source code and realised that for some reason my one kafka cluster through this library reports duplicates of consumer groups .This is why I decided to create a simple script using franz-go lib and compare it with simple python script:

```
#!/usr/bin/env python3

from kafka import KafkaAdminClient
client = KafkaAdminClient(bootstrap_servers="127.0.0.1:9092")
for group in client.list_consumer_groups():
    print(group[0])
```
The above script for all my clusters reports uniq consumer group names.

I did also a small change to kminion in file promeheus/collect_consumer_groups.go which seems to solve my problem

![image](https://github.com/twmb/franz-go/assets/33431714/8bcd79a8-f79f-4dc5-81f4-448bf0d57038)


More details about the kafka cluster I experience the issue:
Env: k8s
Kafka: kafka:2.13-2.6.1
Number of brokers: 12
Number of Consumer Groups: few thousands

**Comment by twmb** [comment] 2023-09-21 13:07
The kmsg package is largely autogenerated and isn't recommended to be used directly -- it's a bit more advanced. If you're trying to reproduce what you're seeing in kminion, yes you'll probably need to use kmsg. If you just want to list groups, you can use [kadm.ListGroups](https://pkg.go.dev/github.com/twmb/franz-go/pkg/kadm#Client.ListGroups), although this automatically deduplicates if there are any duplicates.

Your panic is because you're converting a ListGroupsResponse to a DescribeGroupsResponse.

The reason you're not getting duplicates (_if_ there are duplicates) in the Python code is because the Python code also automatically deduplicates,
https://github.com/dpkp/kafka-python/blob/a33fcf4d22bdf34e9660e394a7a6f84225411325/kafka/admin/client.py#L1166C19-L1174
note that `consumer_groups` is a `set`.

What I'd like you to do is:
```go
shards := cl.RequestSharded(context.Background, kmsg.NewPtrListGroupsRequest())
for _, shard := range shards {
    if shard.Err != nil {
        fmt.Printf("unable to request node %d: %v\n", shard.Meta.NodeID, shard.Err)
        continue
    }
    resp := shard.Resp.(*kmsg.ListGroupsResponse)
    var groups []string
    for _, group := range resp.Groups {
        groups = append(groups, group.Group)
    }
    fmt.Printf("node %d req err: %v, groups: %v\n", shard.Meta.NodeID, resp.ErrorCode, groups)
}
```

**Comment by twmb** [comment] 2023-09-21 13:11
(also kminion was written before kadm existed and kminion should be migrated to kadm, but that's a different prioritization conversation)

**Comment by pawelcit** [comment] 2023-09-21 13:27
Does it mean that there is a bug in kminion or I have some issue inside of my kafka cluster?

**Comment by twmb** [comment] 2023-09-21 13:49
I wonder if you ran into the problem that the `set` in the Python code is specifically solving: a race with a coordinator change can cause a group two be on two brokers at _almost_ the same time.

**Comment by pawelcit** [comment] 2023-09-21 14:03
If I analyse correctly the data with duplicates I get then it looks like:
1. Some Consumer Groups are reported 2 or 3 times from the the same broker only. For instance: consumer_group_1 was reporter 3 times from a given broker_1.
2. Some Consumer Groups are reported once.
3. Seems like all brokers (in this case 12) are reporting some Cosumer Groups multiple time. It's not like one broker is affected.

**Comment by twmb** [comment] 2023-09-21 14:27
(1) and (3) shouldn't be the case unless there's a bug in the broker or the client.

**Comment by pawelcit** [comment] 2023-09-21 14:34
Can we consider that the kminion's behavior I'm experiencing is a bug?

**Comment by twmb** [comment] 2023-09-21 14:42
Yes but there isn't currently enough info to debug it. Is there any way to reproduce this reliably, on a cluster I can spin up on my laptop?

**Comment by twmb** [comment] 2023-09-25 14:37
Closing, let me know if this can be reproduced

**Closed by twmb** 2023-09-25 14:37 UTC
Labels: waiting for details
