### ISSUE TITLE
committing offset failed with UNKNOWN_MEMBER_ID

### ISSUE THREAD

**Issue by yuzhichang** [twmb/franz-go#122] opened 2022-01-21 10:18 UTC
Sometimes my app failed to commit offset. Here's the last piece log of my app(some are from franz).

```
{"level":"debug","ts":"2022-01-20T11:24:30.282+0800","msg":"read Fetch v12","broker":"0","bytes_read":2225,"read_wait":0.000052523,"time_to_read":0.677000644,"err":null}
{"level":"debug","ts":"2022-01-20T11:24:30.282+0800","msg":"updated uncommitted","group":"metric-010","to":"perf-metric[0{279790128=>279790160}]"}
{"level":"debug","ts":"2022-01-20T11:24:30.282+0800","msg":"wrote Fetch v12","broker":"0","bytes_written":94,"write_wait":0.000044943,"time_to_write":0.000026953,"err":null}
{"level":"debug","ts":"2022-01-20T11:24:30.283+0800","msg":"read Fetch v12","broker":"0","bytes_read":1297,"read_wait":0.000059019,"time_to_read":0.000315609,"err":null}
{"level":"debug","ts":"2022-01-20T11:24:30.283+0800","msg":"updated uncommitted","group":"metric-010","to":"perf-metric[0{279790160=>279790176}]"}
{"level":"debug","ts":"2022-01-20T11:24:30.283+0800","msg":"wrote Fetch v12","broker":"0","bytes_written":94,"write_wait":0.000034503,"time_to_write":0.000022079,"err":null}
{"level":"debug","ts":"2022-01-20T11:24:30.316+0800","msg":"stopping task service...","task":"sink-metric"}
{"level":"debug","ts":"2022-01-20T11:24:30.316+0800","msg":"stopped internal timers","task":"sink-metric"}
{"level":"info","ts":"2022-01-20T11:24:30.316+0800","msg":"assigning partitions","why":"invalidating all assignments in LeaveGroup","how":"unassigning everything","input":""}
{"level":"debug","ts":"2022-01-20T11:24:30.316+0800","msg":"read Fetch v12","broker":"0","bytes_read":0,"read_wait":0.000037838,"time_to_read":0.033312478,"err":"context canceled"}
{"level":"debug","ts":"2022-01-20T11:24:30.316+0800","msg":"read from broker errored, killing connection","addr":"192.168.31.170:9092","broker":"0","successful_reads":899,"err":"context canceled"}
{"level":"debug","ts":"2022-01-20T11:24:30.316+0800","msg":"read Fetch v12","broker":"2","bytes_read":0,"read_wait":0.000043614,"time_to_read":0.584008649,"err":"context canceled"}
{"level":"debug","ts":"2022-01-20T11:24:30.317+0800","msg":"read from broker errored, killing connection","addr":"192.168.31.172:9092","broker":"2","successful_reads":1336,"err":"context canceled"}
{"level":"info","ts":"2022-01-20T11:24:30.324+0800","msg":"heartbeat errored","group":"metric-010","err":"context canceled"}
{"level":"debug","ts":"2022-01-20T11:24:30.324+0800","msg":"entering OnRevoked","with":{"perf-metric":[0,1,2]}}
{"level":"debug","ts":"2022-01-20T11:24:58.131+0800","msg":"reaped connections","time_since_last_reap":19.999779839,"reap_dur":0.000056721,"num_reaped":1}
{"level":"debug","ts":"2022-01-20T11:26:38.139+0800","msg":"opening connection to broker","addr":"192.168.31.170:9092","broker":"0"}
{"level":"debug","ts":"2022-01-20T11:26:38.139+0800","msg":"connection opened to broker","addr":"192.168.31.170:9092","broker":"0"}
{"level":"debug","ts":"2022-01-20T11:26:38.139+0800","msg":"connection initialized successfully","addr":"192.168.31.170:9092","broker":"0"}
{"level":"debug","ts":"2022-01-20T11:26:38.139+0800","msg":"wrote Metadata v11","broker":"0","bytes_written":51,"write_wait":0.000305269,"time_to_write":0.000015978,"err":null}
{"level":"debug","ts":"2022-01-20T11:26:38.139+0800","msg":"read Metadata v11","broker":"0","bytes_read":257,"read_wait":0.000086944,"time_to_read":0.000163227,"err":null}
{"level":"debug","ts":"2022-01-20T11:26:38.139+0800","msg":"metadata refresh has identical topic partition data","topic":"perf-metric","partition":0,"leader":0,"leader_epoch":3}
{"level":"debug","ts":"2022-01-20T11:26:38.139+0800","msg":"metadata refresh has identical topic partition data","topic":"perf-metric","partition":1,"leader":2,"leader_epoch":4}
{"level":"debug","ts":"2022-01-20T11:26:38.139+0800","msg":"metadata refresh has identical topic partition data","topic":"perf-metric","partition":2,"leader":0,"leader_epoch":3}
{"level":"debug","ts":"2022-01-20T11:27:18.131+0800","msg":"reaped connections","time_since_last_reap":20.000436196,"reap_dur":0.000063258,"num_reaped":1}
{"level":"debug","ts":"2022-01-20T11:31:07.935+0800","msg":"in CommitOffsetsSync","group":"metric-010","with":{"perf-metric":{"2":{"Epoch":-1,"Offset":29747354}}}}
{"level":"debug","ts":"2022-01-20T11:31:07.935+0800","msg":"issuing commit","group":"metric-010","uncommitted":{"perf-metric":{"2":{"Epoch":-1,"Offset":29747354}}}}
{"level":"debug","ts":"2022-01-20T11:31:07.935+0800","msg":"opening connection to broker","addr":"192.168.31.170:9092","broker":"0"}
{"level":"debug","ts":"2022-01-20T11:31:07.935+0800","msg":"connection opened to broker","addr":"192.168.31.170:9092","broker":"0"}
{"level":"debug","ts":"2022-01-20T11:31:07.935+0800","msg":"connection initialized successfully","addr":"192.168.31.170:9092","broker":"0"}
{"level":"debug","ts":"2022-01-20T11:31:07.935+0800","msg":"wrote OffsetCommit v8","broker":"0","bytes_written":149,"write_wait":0.000232615,"time_to_write":0.000017193,"err":null}
{"level":"debug","ts":"2022-01-20T11:31:07.936+0800","msg":"read OffsetCommit v8","broker":"0","bytes_read":36,"read_wait":0.000071913,"time_to_read":0.000341584,"err":null}
{"level":"warn","ts":"2022-01-20T11:31:08.029+0800","msg":"unable to commit offset for topic partition","group":"metric-010","topic":"perf-metric","partition":2,"commit_from":29746158,"commit_to":29747354,"commit_epoch":-1,"error_code":25}
{"level":"debug","ts":"2022-01-20T11:31:08.029+0800","msg":"updated committed","group":"metric-010","to":"perf-metric[]"}
{"level":"debug","ts":"2022-01-20T11:31:08.029+0800","msg":"left CommitOffsetsSync","group":"metric-010"}
{"level":"fatal","ts":"2022-01-20T11:31:08.029+0800","msg":"Batch.Commit failed with permanent error","task":"sink-metric","error":"UNKNOWN_MEMBER_ID: The coordinator is not aware of this member.","stacktrace":"github.com/housepower/clickhouse_sinker/output.(*ClickHouse).loopWrite\n\t/data01/zhichyu/clickhouse_sinker/output/clickhouse.go:178\ngithub.com/housepower/clickhouse_sinker/output.(*ClickHouse).Send.func1\n\t/data01/zhichyu/clickhouse_sinker/output/clickhouse.go:99\ngithub.com/housepower/clickhouse_sinker/util.(*WorkerPool).wokerFunc\n\t/data01/zhichyu/clickhouse_sinker/util/workerpool.go:59"}

```

`github.com/twmb/franz-go v1.2.4`

**Comment by yuzhichang** [comment] 2022-01-22 01:52
```
	opts := []kgo.Opt{
                ...
		kgo.DisableAutoCommit(),
		kgo.OnPartitionsRevoked(k.onPartitionRevoked),
	}
	if k.cl, err = kgo.NewClient(opts...); err != nil {
        ...

func (k *KafkaFranz) onPartitionRevoked(_ context.Context, _ *kgo.Client, _ map[string][]int32) {
	k.cleanupFn() //This func waits all flying batches be written to database and committed to Kafka. UNKNOWN_MEMBER_ID is throwed during this func. My question is, has this client leaved the group at this point?
}
```

**Comment by twmb** [comment] 2022-01-23 04:33
The two key lines in the above are:
```
{"level":"debug","ts":"2022-01-20T11:24:30.324+0800","msg":"entering OnRevoked","with":{"perf-metric":[0,1,2]}}
...
{"level":"debug","ts":"2022-01-20T11:31:07.935+0800","msg":"in CommitOffsetsSync","group":"metric-010","with":{"perf-metric":{"2":{"Epoch":-1,"Offset":29747354}}}}
```
so, it looks like 5m37s elapsed between the group beginning a rebalance state, and your code committing. If I'm reading the code sample correctly, your `onPartitionsRevoked` waits for everything to be done and then commits, and only after that, leaves the revoke.

Kafka groups have a rebalance timeout and a session timeout -- by default, the rebalance timeout is 60s. If your client is taking longer than 60s, Kafka decides to not wait for the client anymore and allow a rebalance with the other members to continue. When you finally go to issue the commit 5min later, the client is using its current group generation (which is incremented after every rebalance). The generation is out of date, and Kafka rejects the commit.

What is your rebalance timeout? If 60s, you may want to consider either increasing the timeout, or decreasing the time it takes to commit to the DB and then commit to Kafka.

**Comment by yuzhichang** [comment] 2022-01-23 13:19
Thanks for your help. My rebalance timeout is the default 60s. I'll add more log to understand why writing to DB is so slow.

**Comment by twmb** [comment] 2022-01-28 02:25
Cool, glad this was able to help a bit. Closing for now, feel free to reopen if you think the issue is unresolved!

**Closed by twmb** 2022-01-28 02:25 UTC

**Comment by topofstack** [comment] 2024-07-17 13:26
Hi @twmb, i've been having the same issue, but the problem is that `UNKNOWN_MEMBER_ID` keeps popping up even after rebalance is done and kicked out consumer rejoins.


So, it looks like group member is stuck in neverending loop of relabances and `in default commit: unable to commit offsets for topic partition` messages. I've tried to reintialize franz-client with no avail.

**Comment by twmb** [comment] 2024-07-22 17:55
@topofstack what do debug logs look like?
