### ISSUE TITLE
Azure: goroutine_per_partition_consuming example getting kicked out of consumer group

### ISSUE THREAD

**Issue by stampy88** [twmb/franz-go#527] opened 2023-07-31 14:20 UTC
Hi,

Having an issue on Azure where my consumer, which is very much based on your https://github.com/twmb/franz-go/tree/master/examples/goroutine_per_partition_consuming/manual_commit example, keeps getting kicked out of the consumer group. From the Azure side it says that the heartbeat timed out, but when debug logs are enabled you do see if hearbeating successfully so something is definitely weird. To ensure I wasn't doing something wrong, I took your example with just modifications to match the configuration of my consumer (I am posting that below). The Event Hub topic I am listening to, and I was the only consumer in my group for the test with your code, was getting around 400 events/sec. I am going to see if I start up the "example code" based consumer, and see if it gets bounced from a topic without any events coming in. I am hoping that since this is the example code, you'll be able to see recreate the error as well. Oh, speaking of which, you get a `Fetch error: unable to join group session: UNKNOWN_MEMBER_ID: The coordinator is not aware of this member. t:  p: 0` since you were kicked out of the group.

```
package main

import (
	"context"
	"crypto/tls"
	"flag"
	"fmt"
	"math/rand"
	"net"
	"os"
	"os/signal"
	"sync"
	"syscall"
	"time"

	"github.com/twmb/franz-go/pkg/kgo"
	"github.com/twmb/franz-go/pkg/sasl/plain"
)

type tp struct {
	t string
	p int32
}

type pconsumer struct {
	cl        *kgo.Client
	topic     string
	partition int32

	quit chan struct{}
	done chan struct{}
	recs chan []*kgo.Record
}

type splitConsume struct {
	// Using BlockRebalanceOnCommit means we do not need a mu to manage
	// consumers, unlike the autocommit normal example.
	consumers map[tp]*pconsumer
}

func (pc *pconsumer) consume() {
	defer close(pc.done)
	fmt.Printf("Starting consume for  t %s p %d\n", pc.topic, pc.partition)
	defer fmt.Printf("Closing consume for t %s p %d\n", pc.topic, pc.partition)
	for {
		select {
		case <-pc.quit:
			return
		case recs := <-pc.recs:
			time.Sleep(time.Duration(rand.Intn(150)+100) * time.Millisecond) // simulate work
			fmt.Printf("Some sort of work done, about to commit t %s p %d\n", pc.topic, pc.partition)
			err := pc.cl.CommitRecords(context.Background(), recs...)
			if err != nil {
				fmt.Printf("Error when committing offsets to kafka err: %v t: %s p: %d offset %d\n", err, pc.topic, pc.partition, recs[len(recs)-1].Offset+1)
			}
		}
	}
}

func (s *splitConsume) assigned(_ context.Context, cl *kgo.Client, assigned map[string][]int32) {
	for topic, partitions := range assigned {
		for _, partition := range partitions {
			pc := &pconsumer{
				cl:        cl,
				topic:     topic,
				partition: partition,

				quit: make(chan struct{}),
				done: make(chan struct{}),
				recs: make(chan []*kgo.Record, 5),
			}
			s.consumers[tp{topic, partition}] = pc
			go pc.consume()
		}
	}
}

// In this example, each partition consumer commits itself. Those commits will
// fail if partitions are lost, but will succeed if partitions are revoked. We
// only need one revoked or lost function (and we name it "lost").
func (s *splitConsume) lost(_ context.Context, cl *kgo.Client, lost map[string][]int32) {
	var wg sync.WaitGroup
	defer wg.Wait()

	for topic, partitions := range lost {
		for _, partition := range partitions {
			tp := tp{topic, partition}
			pc := s.consumers[tp]
			delete(s.consumers, tp)
			close(pc.quit)
			fmt.Printf("waiting for work to finish t %s p %d\n", topic, partition)
			wg.Add(1)
			go func() { <-pc.done; wg.Done() }()
		}
	}
}

func main() {
	rand.Seed(time.Now().Unix())
	flag.Parse()

	s := &splitConsume{
		consumers: make(map[tp]*pconsumer),
	}

	dialer := &tls.Dialer{NetDialer: &net.Dialer{Timeout: 5 * time.Second}, Config: &tls.Config{InsecureSkipVerify: true}}

	opts := []kgo.Opt{
		kgo.SeedBrokers("XXXX.servicebus.windows.net:9093"),
		kgo.ConsumerGroup("dataformatter"),
		kgo.SASL(plain.Auth{User: "$ConnectionString", Pass: "XXXXXX"}.AsMechanism()),
		kgo.ConsumeTopics("oss.dev.v1"),
		kgo.ConnIdleTimeout(3 * time.Minute),
		kgo.Dialer(dialer.DialContext),
		kgo.SessionTimeout(45 * time.Second),
		kgo.FetchMaxBytes(100000),
		kgo.FetchMinBytes(50000),
		kgo.RequestTimeoutOverhead(1 * time.Minute),
		kgo.MetadataMaxAge(3 * time.Minute),
		kgo.OnPartitionsAssigned(s.assigned),
		kgo.OnPartitionsRevoked(s.lost),
		kgo.OnPartitionsLost(s.lost),
		kgo.DisableAutoCommit(),
		kgo.BlockRebalanceOnPoll(),
	}

	cl, err := kgo.NewClient(opts...)
	if err != nil {
		panic(err)
	}
	if err = cl.Ping(context.Background()); err != nil { // check connectivity to cluster
		panic(err)
	}

	ch := make(chan os.Signal, 1)

	// can't catch SIGKILL in GO so leaving it out
	signal.Notify(ch, os.Interrupt, syscall.SIGINT, syscall.SIGTERM)

	// block until signal is Received
	go func() {
		_ = <-ch
		fmt.Println("Caught shutdown signal; shutting down client...")
		cl.Close()
		fmt.Println("Caught shutdown signal; shutting down client...complete")
		os.Exit(1)
	}()

	s.poll(cl)
}

func (s *splitConsume) poll(cl *kgo.Client) {
	for {
		// PollRecords is strongly recommended when using
		// BlockRebalanceOnPoll. You can tune how many records to
		// process at once (upper bound -- could all be on one
		// partition), ensuring that your processor loops complete fast
		// enough to not block a rebalance too long.
		fetches := cl.PollFetches(context.Background())
		if fetches.IsClientClosed() {
			return
		}
		fetches.EachError(func(t string, p int32, err error) {
			// Note: you can delete this block, which will result
			// in these errors being sent to the partition
			// consumers, and then you can handle the errors there.
			fmt.Printf("Fetch error: %v t: %s p: %d\n", err, t, p)
		})
		fetches.EachPartition(func(p kgo.FetchTopicPartition) {
			tp := tp{p.Topic, p.Partition}

			// Since we are using BlockRebalanceOnPoll, we can be
			// sure this partition consumer exists:
			//
			// * onAssigned is guaranteed to be called before we
			// fetch offsets for newly added partitions
			//
			// * onRevoked waits for partition consumers to quit
			// and be deleted before re-allowing polling.
			s.consumers[tp].recs <- p.Records
		})
		cl.AllowRebalance()
	}
}

**Comment by stampy88** [comment] 2023-07-31 14:30
Oh, the topic has 50 partitions. Not sure if that is relevant yet.

**Comment by twmb** [comment] 2023-07-31 17:24
> I am going to see if I start up the "example code" based consumer, and see if it gets bounced from a topic without any events coming in

Does it?

If not, how long is your consumer stuck processing in consume? Also, what happens if you take out block rebalance on poll (and the allow rebalance)? Note that you'll double process records (i.e. what block rebalance is meant to prevent) -- but if this fixes it, that'll point to your consume taking too long / blocking a rebalance for so long. It doesn't matter if this is a size-1 group, if your 1 member takes more than the session timeout to close out and allow a rebalance, then the member is kicked.

**Comment by stampy88** [comment] 2023-07-31 20:46
@twmb , I am not doing a good job explaining myself. The code above (your example code) was getting bounced on a topic with 50 partitions and ~400 events/sec.  What I was testing, was whether it had anything to do with events coming into the topic or not. The answer is it doesn't matter whether events come or not. I have a another topic with 3 partitions and which saw zero events for the last 24 hours. That just got the same problem:
`Fetch error: unable to join group session: UNKNOWN_MEMBER_ID: The coordinator is not aware of this member. t:  p: 0` - so it seems like something with this example and Azure.

**Comment by stampy88** [comment] 2023-07-31 20:47
This problem also causes that code to panic, which I think someone else had mentioned:
```
Fetch error: unable to join group session: UNKNOWN_MEMBER_ID: The coordinator is not aware of this member. t:  p: 0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x71cc99]

goroutine 1 [running]:
main.(*splitConsume).poll.func2({{0x0, 0x0}, {0x0, {0x861a20, 0xc00048a5a0}, 0x0, 0x0, 0x0, {0x0, 0x0, ...}}})
	/home/dave/projects/xxxx/main.go:182 +0x59
github.com/twmb/franz-go/pkg/kgo.Fetches.EachPartition({0xc0001826a8?, 0x1, 0xc0000a0000?}, 0xc000105dd0)
	/home/dave/go/pkg/mod/github.com/twmb/franz-go@v1.14.1/pkg/kgo/record_and_fetch.go:520 +0x178
main.(*splitConsume).poll(0xc0000ac038, 0xc000120000)
	/home/dave/projects/xxxxx/main.go:171 +0x74
main.main()
	/home/dave/projects/xxxx/main.go:151 +0xcdc

**Comment by twmb** [comment] 2023-08-01 16:30
Yes that sounds identical to #518 which I would love to know how to reliably trigger in a test.

No clue about the unknown member ID bit. It almost sounds like either the client is deadlocked in a revoke goroutine, or Azure is expiring the member ID for now reason.

**Comment by stampy88** [comment] 2023-08-01 16:42
Here's the [log](https://github.com/twmb/franz-go/files/12232025/franz.log) using the above code. I did see this in there
`[DEBUG] sharded request failed, resharding and reissuing; req: FindCoordinator, time_since_start: 23.298427ms, tries: 0, err: broker is too old; the broker has already indicated it will not know how to handle the request`.

**Comment by twmb** [comment] 2023-08-01 16:49
That is expected and only visible in debug mode (so I don't care _too_ much about cleaning the log up)
The client first tries a batched request which requires new-protocol support, then the client sees that the broker doesn't support it, doesn't issue the batch request, and just immediately splits it.

**Comment by stampy88** [comment] 2023-08-01 16:56
FYI - response to the `ApiVersionsRequest`: 
```
{
  "Version": 3,
  "ErrorCode": 0,
  "ApiKeys": [
    {
      "ApiKey": 0,
      "MinVersion": 3,
      "MaxVersion": 7,
      "UnknownTags": {}
    },
    {
      "ApiKey": 1,
      "MinVersion": 4,
      "MaxVersion": 6,
      "UnknownTags": {}
    },
    {
      "ApiKey": 2,
      "MinVersion": 0,
      "MaxVersion": 7,
      "UnknownTags": {}
    },
    {
      "ApiKey": 3,
      "MinVersion": 0,
      "MaxVersion": 5,
      "UnknownTags": {}
    },
    {
      "ApiKey": 8,
      "MinVersion": 0,
      "MaxVersion": 8,
      "UnknownTags": {}
    },
    {
      "ApiKey": 9,
      "MinVersion": 0,
      "MaxVersion": 8,
      "UnknownTags": {}
    },
    {
      "ApiKey": 10,
      "MinVersion": 0,
      "MaxVersion": 1,
      "UnknownTags": {}
    },
    {
      "ApiKey": 11,
      "MinVersion": 0,
      "MaxVersion": 7,
      "UnknownTags": {}
    },
    {
      "ApiKey": 12,
      "MinVersion": 0,
      "MaxVersion": 4,
      "UnknownTags": {}
    },
    {
      "ApiKey": 13,
      "MinVersion": 0,
      "MaxVersion": 4,
      "UnknownTags": {}
    },
    {
      "ApiKey": 14,
      "MinVersion": 0,
      "MaxVersion": 5,
      "UnknownTags": {}
    },
    {
      "ApiKey": 15,
      "MinVersion": 0,
      "MaxVersion": 5,
      "UnknownTags": {}
    },
    {
      "ApiKey": 16,
      "MinVersion": 0,
      "MaxVersion": 4,
      "UnknownTags": {}
    },
    {
      "ApiKey": 17,
      "MinVersion": 0,
      "MaxVersion": 1,
      "UnknownTags": {}
    },
    {
      "ApiKey": 18,
      "MinVersion": 0,
      "MaxVersion": 3,
      "UnknownTags": {}
    },
    {
      "ApiKey": 19,
      "MinVersion": 0,
      "MaxVersion": 6,
      "UnknownTags": {}
    },
    {
      "ApiKey": 20,
      "MinVersion": 0,
      "MaxVersion": 2,
      "UnknownTags": {}
    },
    {
      "ApiKey": 22,
      "MinVersion": 0,
      "MaxVersion": 1,
      "UnknownTags": {}
    },
    {
      "ApiKey": 23,
      "MinVersion": 0,
      "MaxVersion": 0,
      "UnknownTags": {}
    },
    {
      "ApiKey": 32,
      "MinVersion": 0,
      "MaxVersion": 2,
      "UnknownTags": {}
    },
    {
      "ApiKey": 36,
      "MinVersion": 0,
      "MaxVersion": 1,
      "UnknownTags": {}
    },
    {
      "ApiKey": 37,
      "MinVersion": 0,
      "MaxVersion": 1,
      "UnknownTags": {}
    },
    {
      "ApiKey": 42,
      "MinVersion": 0,
      "MaxVersion": 0,
      "UnknownTags": {}
    },
    {
      "ApiKey": 47,
      "MinVersion": 0,
      "MaxVersion": 0,
      "UnknownTags": {}
    }
  ],
  "ThrottleMillis": 0,
  "SupportedFeatures": null,
  "FinalizedFeaturesEpoch": -1,
  "FinalizedFeatures": null,
  "ZkMigrationReady": false,
  "UnknownTags": {}
}

**Comment by twmb** [comment] 2023-08-01 17:02
Yes that's fine, Azure has limited support but covers a lot of the important bits.

**Comment by stampy88** [comment] 2023-08-02 13:32
Ran again with timestamps and dumped the stacks: [franz_aug_1.log](https://github.com/twmb/franz-go/files/12240499/franz_aug_1.log). Doesn't show much besides the last read heartbeat took 6 seconds which is way higher than normal. I am going to try with the confluent client, set up similarly, i.e. create go routines on the rebalance callback, and see if the same error occurs. MS support has been useless in troubleshooting this. Note that the issue does not occur right away; it took 3.5 hours for it to happen the last time.

**Comment by twmb** [comment] 2023-08-02 20:56
Was the link temporary? I can't download it -- however, I'm getting econnreset and am on public wifi, so perhaps it's the wifi where I'm at.

Let me know how this goes with confluent, I'm quite curious if it works on their client -- if so, that's a really odd disparity.

**Comment by stampy88** [comment] 2023-08-03 13:53
No, it's not temporary. It's working for me still. I'll let you know how it goes with confluent as soon as I have it running for long enough.

**Comment by twmb** [comment] 2023-08-03 14:37
I see the logs, must have been the network I was on.
The panic at the end -- that's something I'd like to investigate separately, but am very interested in trying to recreate. I suspect I can find the problem if I stare at the code long enough, and might just go that route if I (we / you 😅) can't figure out an easy reproducer ahead of time.

**Comment by stampy88** [comment] 2023-08-03 17:24
well, good news for you; I got kicked using confluent :smile: 
```
Kafka Logs:  [2023-08-03T16:48:29Z][rdkafka#consumer-1][HEARTBEAT][7][thrd:main]: GroupCoordinator/0: Heartbeat for group "dont-get-kicked" generation id 3
Kafka Logs:  [2023-08-03T16:48:32Z][rdkafka#consumer-1][HEARTBEAT][7][thrd:main]: GroupCoordinator/0: Heartbeat for group "dont-get-kicked" generation id 3
Kafka Logs:  [2023-08-03T16:48:35Z][rdkafka#consumer-1][HEARTBEAT][7][thrd:main]: GroupCoordinator/0: Heartbeat for group "dont-get-kicked" generation id 3
Kafka Logs:  [2023-08-03T16:48:38Z][rdkafka#consumer-1][HEARTBEAT][7][thrd:main]: GroupCoordinator/0: Heartbeat for group "dont-get-kicked" generation id 3
Kafka Logs:  [2023-08-03T16:48:41Z][rdkafka#consumer-1][HEARTBEAT][7][thrd:main]: GroupCoordinator/0: Heartbeat for group "dont-get-kicked" generation id 3
Kafka Logs:  [2023-08-03T16:48:44Z][rdkafka#consumer-1][HEARTBEAT][7][thrd:main]: GroupCoordinator/0: Heartbeat for group "dont-get-kicked" generation id 3
Kafka Logs:  [2023-08-03T16:48:47Z][rdkafka#consumer-1][HEARTBEAT][7][thrd:main]: GroupCoordinator/0: Heartbeat for group "dont-get-kicked" generation id 3
Kafka Logs:  [2023-08-03T16:48:50Z][rdkafka#consumer-1][HEARTBEAT][7][thrd:main]: GroupCoordinator/0: Heartbeat for group "dont-get-kicked" generation id 3
Kafka Logs:  [2023-08-03T16:48:53Z][rdkafka#consumer-1][HEARTBEAT][7][thrd:main]: GroupCoordinator/0: Heartbeat for group "dont-get-kicked" generation id 3
Kafka Logs:  [2023-08-03T16:48:56Z][rdkafka#consumer-1][HEARTBEAT][7][thrd:main]: GroupCoordinator/0: Heartbeat for group "dont-get-kicked" generation id 3
Kafka Logs:  [2023-08-03T16:48:59Z][rdkafka#consumer-1][HEARTBEAT][7][thrd:main]: GroupCoordinator/0: Heartbeat for group "dont-get-kicked" generation id 3
Kafka Logs:  [2023-08-03T16:49:02Z][rdkafka#consumer-1][HEARTBEAT][7][thrd:main]: GroupCoordinator/0: Heartbeat for group "dont-get-kicked" generation id 3
Kafka Logs:  [2023-08-03T16:49:05Z][rdkafka#consumer-1][HEARTBEAT][7][thrd:main]: GroupCoordinator/0: Heartbeat for group "dont-get-kicked" generation id 3
Kafka Logs:  [2023-08-03T16:49:06Z][rdkafka#consumer-1][METADATA][7][thrd:main]:   Topic device-payloads-dl partition 0 Leader 1 Epoch -1
Kafka Logs:  [2023-08-03T16:49:06Z][rdkafka#consumer-1][METADATA][7][thrd:main]:   Topic device-payloads-dl partition 1 Leader 0 Epoch -1
Kafka Logs:  [2023-08-03T16:49:06Z][rdkafka#consumer-1][METADATA][7][thrd:main]:   Topic device-payloads-dl partition 2 Leader 2 Epoch -1
Kafka Logs:  [2023-08-03T16:49:06Z][rdkafka#consumer-1][METADATA][7][thrd:main]: sasl_ssl://XXXX.servicebus.windows.net:9093/2: 1/1 requested topic(s) seen in metadata
Kafka Logs:  [2023-08-03T16:49:08Z][rdkafka#consumer-1][HEARTBEAT][7][thrd:main]: GroupCoordinator/0: Heartbeat for group "dont-get-kicked" generation id 3
Kafka Logs:  [2023-08-03T16:49:11Z][rdkafka#consumer-1][HEARTBEAT][7][thrd:main]: GroupCoordinator/0: Heartbeat for group "dont-get-kicked" generation id 3
Kafka Logs:  [2023-08-03T16:49:14Z][rdkafka#consumer-1][HEARTBEAT][7][thrd:main]: GroupCoordinator/0: Heartbeat for group "dont-get-kicked" generation id 3
Kafka Logs:  [2023-08-03T16:49:15Z][rdkafka#consumer-1][HEARTBEAT][7][thrd:main]: Group "dont-get-kicked" heartbeat error response in state up (join-state steady, 3 partition(s) assigned): Broker: Unknown member

**Comment by twmb** [comment] 2023-08-03 18:02
So I think this is something to punt back to Azure then?
(minus the issue about a panic, there's something in franz-go there)

**Comment by stampy88** [comment] 2023-08-03 18:06
Yes, I gave them this as well, so I'll report back if you are interested.

**Comment by stampy88** [comment] 2023-08-04 15:31
OK, let me get further with MS, then I'll return to recreating this.

**Comment by twmb** [comment] 2023-08-10 17:04
Any luck with this?

**Comment by stampy88** [comment] 2023-08-14 17:21
sorry, haven't had a chance to re-create this. I'l give it a shot later today.

**Comment by twmb** [comment] 2023-08-25 14:45
Any luck reproducing?

**Comment by stampy88** [comment] 2023-09-13 15:43
@twmb so bad news. MS has fixed the issue which was causing that "unknown member id" error so I can't recreate this easily anymore. I can tell you that the issue was related to the group coordinator changing. So not sure if you can easily test with a set of brokers and kill the one that is the coordinator for the consumer group and see if that does it.

**Comment by twmb** [comment] 2023-09-16 14:38
Let's preemptively close this for now and assume it was some bug on their side. This client _should_ be tested against that behavior already because this is used pretty extensively in Redpanda tests, and I think there's a test against a similar behavior you're mentioning... 🤔 
Unfortunate, but please raise again if you run into this.

**Closed by twmb** 2023-09-16 14:38 UTC
Labels: bug, waiting for details
