### ISSUE TITLE
Calculating consumer lag

### ISSUE THREAD

**Issue by tymeshifter** [twmb/franz-go#49] opened 2021-07-20 11:10 UTC
I think I got it form the documentation but wanted to confirm with you because it's not completely clear.

You would need to use this request to get Latest Committed Offset (LCO):
https://pkg.go.dev/github.com/twmb/franz-go@v0.8.7/pkg/kmsg#OffsetFetchRequest
https://pkg.go.dev/github.com/twmb/franz-go@v0.8.7/pkg/kmsg#OffsetFetchResponseTopicPartition

Then send this request to get Latest Partition Offset (LPO):
https://pkg.go.dev/github.com/twmb/franz-go@v0.8.7/pkg/kmsg#ListOffsetsRequest
https://pkg.go.dev/github.com/twmb/franz-go@v0.8.7/pkg/kmsg#ListOffsetsResponseTopicPartition

And LAG for particular group would be:

```
LAG
for each topic
    for each partition
        LAG += LPO - LCO
```

Is this enough or more operations are needed?

**Comment by twmb** [comment] 2021-07-20 18:17
Yep that's the exact sequence of events that are necessary. The only additional minor catch is that this doesn't print the lag for members that have not yet committed, but that's not really possible to do.

As an example of that flow you describe, you can check out `kcl`'s implementation here:
https://github.com/twmb/kcl/blob/master/commands/admin/group/describe.go#L103-L192
That code uses the `Request` function, but `ListOffsets` and potentially `OffsetFetch` should both use `RequestSharded`, which is more resilient to individual node failures.

Another example can be seen in kowl (I think this is the chunk of code):
https://github.com/cloudhut/kowl/blob/0ba03992b1658519719f8ee1e720fa99478d72cd/backend/pkg/owl/consumer_group_offsets.go#L50-L185

Let me know if that helps!
Also if you're open, what are you building? I know @weeco had ideas in the past that an admin client in this repo could be useful. I'm not sure exactly how an admin client should look vs. just giving people the power with raw requests.

**Comment by tymeshifter** [comment] 2021-07-21 14:49
Thank you, I think these examples will come in handy.

I am working on private project so can't share details, but basically we have consumers that are not directly handled by us and we want to monitor their lag and alert human when it gets out of hand. A fairly simple use case.

Java client provides this information out of the box but it's very slow start and memory consuming, and it's also a burden when you want to be Go only.

**Comment by twmb** [comment] 2021-07-21 16:03
One other tip is to always use `kmsg.New` functions to receive structs. These are more forward compatible if Kafka adds new fields. I need to eventually update the code in kcl to be a better example here, the code in kcl existed before the `New` functions in kmsg existed, and I always update any new-field changes in kcl in tandem with franz-go.

**Comment by twmb** [comment] 2021-07-22 17:09
I think this issue is closed, if not please reopen. I think I would like to someday add an admin package to provide these things easily (kadmin or something), but I'd need a lot more of a complete sketch on what the package would look like before attempting that!

**Closed** 2021-10-10 19:54 UTC

**Comment by ns-gzhang** [comment] 2023-06-28 23:10
Hi @twmb I'm new to this great Kafka go driver. Thank you! I encountered the value of LastOffset returned from ListOffsetsRequest is -1. Not sure if that's the expected behavior or due to specific Kafka servers (2.8.1) I tested.
I assume that kadm.ListEndOffsets() would return the real offsets? Thanks.
